replicas: 2

image:
  repository: ghcr.io/datapunchorg/remoteshuffleservice
  tag: k8s-spark-3.2

nodeSelector:
    app: rss
resources:
  requests:
    memory: "40G"
    cpu: "5"
  limits:
    memory: "45G"
    cpu: "5.5"

securityContext:
  runAsGroup: 0
  runAsUser: 0
# configure the shuffle service volume owner as Hadoop user (EMR on EKS is 999:1000, OSS Spark is 1000:1000)
volumeUser: 999
volumeGroup: 1000
volumeMounts:
  - name: spark-local-dir-1
    mountPath: /rss1
volumes:
  - name: spark-local-dir-1
    hostPath:
      path: /local1

command:
  jvmHeapSizeOption: "-Xmx800M"
  # point to a nmve SSD volume as the shuffle data storage, not use root volume.
  # the RSS only supports a single disk so far. Use storage optmized EC2 instance type.
  rootdir: "/rss1"
  dataRetentionMillis: "14400000"  # 4 hours
  nettyAcceptThreads: 4
  nettyWorkerThreads: 40

ports:
  shuffleServer: 9338
  healthcheck: 8080
