# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements. See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License. You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rss
  labels:
    app: rss
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: rss
  serviceName: rss
  template:
    metadata:
      labels:
        app: rss
    spec:  
    {{- if .Values.securityContext }}
      securityContext:
        # set shuffle root directory owner
        runAsUser: {{ .Values.securityContext.runAsUser }}
        runAsGroup: {{ .Values.securityContext.runAsGroup }}   
    # {{- end}} 
    {{- if .Values.volumes }}
      volumes:
    {{- range $volumes := .Values.volumes }}
        - name: {{ $volumes.name }}
          hostPath:
            path: {{ $volumes.hostPath.path }}
    {{- end }}
    {{- end }} 
{{- if .Values.nodeSelector }}
      nodeSelector: {{- .Values.nodeSelector | toYaml | nindent 8 }}
{{- end }}
      containers:
        - name: rss
    {{- if .Values.volumeMounts }}
          volumeMounts:
    {{- range $volumeMounts := .Values.volumeMounts }}
          - name: {{ $volumeMounts.name }}
            mountPath: {{ $volumeMounts.mountPath }}
    {{- end }} 
    {{- end }}   
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          resources:
            requests:
              memory: {{ .Values.resources.requests.memory }}
              cpu:  {{ .Values.resources.requests.cpu }}
            limits:
              memory: {{ .Values.resources.limits.memory }}
              cpu: {{ .Values.resources.limits.cpu }}
          env:
            - name: RSS_SERVER_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          command: ["java", "{{ .Values.command.jvmHeapSizeOption }}", "-Dlog4j.configuration=log4j-remote-shuffle-service.properties", "-cp", "remote-shuffle-service-server.jar", "com.uber.rss.StreamServer", "-port", "9338", "-httpPort", "8080","-rootDir","{{ .Values.command.rootdir }}"]
          args: []
          ports:
            - containerPort: {{ .Values.ports.shuffleServer }}
            - containerPort: {{ .Values.ports.healthcheck }}
              name: healthcheck
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: healthcheck
            failureThreshold: 3
            periodSeconds: 15
